name: academic_phd_students
type: csv
path: sources/academic_phd_students.csv
fields:
  - source: id
    alias: id
  - source: name
    alias: name
  - source: h_index
    alias: h_index
    cast: int
  - source: publication_count
    alias: publication_count
    cast: int
  - source: join_year
    alias: join_year
    cast: int
  - source: email
    alias: email
  - source: department_id
    alias: department_id
  - source: advisor_id
    alias: advisor_id
