name: census_states
type: api
url: https://api.census.gov/data/2020/dec/pl
params:
  get: "NAME,P1_001N"
  for: "state:*"
response_format: census_array
cache: true
fields:
  - source: NAME
    alias: name
  - source: P1_001N
    alias: population
    cast: int
  - source: state
    alias: fips
