name: sample_individuals
type: csv
path: sources/sample_individuals.csv
fields:
  - source: id
    alias: id
  - source: name
    alias: name
  - source: municipality
    alias: municipality
  - source: income
    alias: income
    cast: float
