"""Generate provenance-backed HTML dashboards from project analysis artifacts."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def render_dashboard_html(
    *,
    title: str,
    summary_markdown_path: str,
    db_stats: dict[str, Any],
    sources: list[dict[str, Any]] | None = None,
) -> str:
    """Build a self-contained HTML dashboard from hydrated series stats."""
    sources = sources or []

    def _row(label: str, stat: dict[str, Any]) -> str:
        return (
            f"<tr><td>{html.escape(label)}</td>"
            f"<td>{html.escape(str(stat.get('start', '')))} → {html.escape(str(stat.get('end', '')))}</td>"
            f"<td>{stat.get('first', 0):.2f}</td>"
            f"<td>{stat.get('last', 0):.2f}</td>"
            f"<td>{stat.get('pct_change', 0):+.1f}%</td>"
            f"<td>{stat.get('count', 0)}</td></tr>"
        )

    series_rows = []
    labels = {
        "hpi": "NJ House Price Index (NJSTHPI)",
        "unemp": "NJ Unemployment (NJURN)",
        "cpi": "CPI All Urban (CPIAUCSL)",
    }
    for key, label in labels.items():
        if key in db_stats:
            series_rows.append(_row(label, db_stats[key]))

    source_rows = "".join(
        f"<li><strong>{html.escape(s.get('title', s.get('source_key', 'source')))}</strong> "
        f"— {html.escape(s.get('origin', s.get('url_or_path', '')))}</li>"
        for s in sources
    )

    real_affordability = None
    if "hpi" in db_stats and "cpi" in db_stats:
        real_affordability = db_stats["hpi"].get("pct_change", 0) - db_stats["cpi"].get("pct_change", 0)

    highlights = [
        f"Nominal HPI change: {db_stats.get('hpi', {}).get('pct_change', 0):+.1f}%"
        if "hpi" in db_stats
        else None,
        f"Real affordability proxy (HPI − CPI): {real_affordability:+.1f}%"
        if real_affordability is not None
        else None,
        f"Latest unemployment: {db_stats.get('unemp', {}).get('last', 0):.1f}%"
        if "unemp" in db_stats
        else None,
    ]
    highlight_html = "".join(f"<li>{html.escape(item)}</li>" for item in highlights if item)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; color: #111; background: #fafafa; }}
    h1 {{ margin-bottom: 0.25rem; }}
    .meta {{ color: #555; margin-bottom: 1.5rem; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; background: #fff; }}
    th, td {{ border: 1px solid #ddd; padding: 0.5rem 0.75rem; text-align: left; }}
    th {{ background: #f0f4f8; }}
    section {{ margin: 1.5rem 0; }}
    .card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  <p class="meta">Generated by RAIL artifact dashboard service. Analysis: <code>{html.escape(summary_markdown_path)}</code></p>

  <section class="card">
    <h2>Key findings</h2>
    <ul>{highlight_html}</ul>
  </section>

  <section class="card">
    <h2>Series summary</h2>
    <table>
      <thead>
        <tr><th>Series</th><th>Period</th><th>Start</th><th>End</th><th>Change</th><th>N</th></tr>
      </thead>
      <tbody>
        {''.join(series_rows)}
      </tbody>
    </table>
  </section>

  <section class="card">
    <h2>Sources</h2>
    <ul>{source_rows}</ul>
  </section>
</body>
</html>
"""


def write_dashboard_artifact(
    project_root: str | Path,
    *,
    db_stats: dict[str, Any],
    title: str = "Research Dashboard",
    summary_markdown_path: str = "artifacts/nj_housing_affordability_analysis.md",
    sources: list[dict[str, Any]] | None = None,
    artifact_path: str = "artifacts/dashboard.html",
) -> Path:
    """Write dashboard HTML and return the path."""
    root = Path(project_root).resolve()
    out = root / artifact_path
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        render_dashboard_html(
            title=title,
            summary_markdown_path=summary_markdown_path,
            db_stats=db_stats,
            sources=sources,
        ),
        encoding="utf-8",
    )
    return out
